### ISSUE TITLE
Missing Game.ini file

### ISSUE THREAD

**Issue by TheRealShadow** [mschnitzer/ark-survival-ascended-linux-container-image#10]
Everything seems to work great so far (using it now for 4 days). Only issue I'm encountering so far is that the game.ini isn't available. Due to this I can not change the breed settings.

This should be in the same folder as the GameUserSettings.ini

**Comment by mschnitzer** [comment]
The `Game.ini` is not there by default you need to create it.

One example with some maturation and breeding settings:

```
[/script/shootergame.shootergamemode]
EggHatchSpeedMultiplier=5.0
BabyMatureSpeedMultiplier=5.0
BabyImprintAmountMultiplier=20.0
BabyCuddleGracePeriodMultiplier=100.0
BabyCuddleLoseImprintQualitySpeedMultiplier=0.0
BabyCuddleIntervalMultiplier=0.1
```

**Comment by TheRealShadow** [comment]
Is that by game design or the docker design? I'll attempt this fix tonight. Might be useful for the administration documentation

**Comment by mschnitzer** [comment]
This is how the server files are being delivered by Wildcard. The container image is not changing them in any way, so this is independent of the container image's design. There's a already a [section in the README](https://github.com/mschnitzer/ark-survival-ascended-linux-container-image#5-server-configuration) that explains the absence of the `Game.ini` file.

What I could do, is to create the `Game.ini` file by the start script if it is not there and then populate it with some default settings.

**Comment by TheRealShadow** [comment]
I think that might be useful for more people (like me). If it's not too much work.

**Comment by mschnitzer** [comment]
I think that's reasonable and I created #12 for that. Let's close this issue as it seem to have been solved and I'm going to implement this request as a feature in one of the upcoming updates.
