### ISSUE TITLE
RCON Questions

### ISSUE THREAD

**Issue by DarkVentHead** [mschnitzer/ark-survival-ascended-linux-container-image#15]
I have the pre-requisites for RCON under GamUserSettings.ini. Also filed under [Serversettings] Tab. I attempt to execute the RCON command through docker and i get:

command: docker exec -t asa-server asa-ctrl rcon --exec 'saveworld'
Response: World Saved

Is there a way to confirm the actual saving of the world? Mod dates?
------------------------------------------------------------------------------------
command: docker exec -t asa-server asa-ctrl rcon --exec 'serverchat hello!'
response: Server received, but no response!!

But in fact it DID send the serverchat message and can be seen. Is this expected RCON behavior?
------------------------------------------------------------------------------------------------------------------
command: docker exec -t asa-server asa-ctrl rcon --exec 'broadcast hello!'
response: Server received, but no response!!

In this instance. The server does NOT receive the broadcast and nothing pops up. Can the broadcast command not be used with RCON?
------------------------------------------------------------------------------------------------------------------------------------------
I very much appreciate what you're putting together here. Thank you for taking the time to make it all work!

**Comment by DarkVentHead** [comment]
I've used the broadcast command in with admincheat in-game. It pops up like the welcome message does for all players. I know it works for ASA (due to aforementioned reasons).

**Comment by mschnitzer** [comment]
You are right, I tested it myself. However, I think this is not an issue with `asa-ctrl`, as it just passes everything to the server without modifying the content you are passing. It might just not be an RCON command.

**Comment by mschnitzer** [comment]
I'm closing this issue for now, as it doesn't seem to be a bug with the software. Please reopen if this is working in another RCON software, but not in `asa-ctrl`.
