### ISSUE TITLE
How do I add a Password to the Server?

### ISSUE THREAD

**Issue by christian-hager** [mschnitzer/ark-survival-ascended-linux-container-image#16]
Hey there. Could you give me a hint on how to add a password to the server? I tried adding ServerPassword to the Startup-Parameters and to the GameUserSettings.ini but neither seems to work.

**Comment by DarkVentHead** [comment]
In GameUserSettings.ini, It has to be under the section labeled [ServerSettings]

[ServerSettings]
ServerPassword=mypassword

After verifying that it's there by going to (as root): /var/lib/docker/volumes/opt_server-files-1/_data/ShooterGame/Saved/Config/WindowsServer/GameUserSettings.ini

**Comment by christian-hager** [comment]
Thanks, setting the password in the GameUserSettings.ini did actually work today, not sure why it didn't yesterday.

**Comment by christian-hager** [comment]
Thanks, setting the password in the GameUserSettings.ini did actually work today, not sure why it didn't yesterday.
