### ISSUE TITLE
RCON command execution

### ISSUE THREAD

**Issue by mschnitzer** [mschnitzer/ark-survival-ascended-linux-container-image#2]
Admins should be able to execute RCON commands inside the container.

e.g.
```
docker exec asa-server rcon admincheat saveworld
```

**Comment by njakes** [comment]
Is saveworld the only available command for asa-ctrl at this time?

**Comment by mschnitzer** [comment]
Nope, that was just an example. I don't have a list of all supported ones for ASA though. I suggest to try whatever worked for ASE.

**Comment by mschnitzer** [comment]
I noted down some more examples in this section of the README:
https://github.com/mschnitzer/ark-survival-ascended-linux-container-image#daily-restarts

**Comment by mschnitzer** [comment]
Closing this issue now, as it was a tracker for a feature that has meanwhile been implemented.

Here's the official documentation of how to execute RCON commands on your server, through the container:
https://github.com/mschnitzer/ark-survival-ascended-linux-container-image#executing-rcon-commands

If you experience any issues, feel free to open an issue here.
