### ISSUE TITLE
Game.ini not loaded

### ISSUE THREAD

**Issue by Powershooter83** [mschnitzer/ark-survival-ascended-linux-container-image#20]
I have tried to load my own Game.ini file, but without success. I have saved the Game.ini file under /var/lib/docker/volumes/asaserver_server-files-1/_data/ShooterGame/Saved/Config/WindowsServer (I have it from a single player world) unfortunately these settings have no effect.

Thanks for the help :)

**Comment by mschnitzer** [comment]
Hi,

how did you identify it is not being loaded? If you run `ls -l` what permissions does the Game.ini file have? How did you restart the server once you placed the `Game.ini` file? Also please paste the content of it.

**Comment by Powershooter83** [comment]
Hey,

For example, I have adjusted the Game.ini so that damage values are displayed.
(Works locally, but not on the server)
The Game.ini file has the following rights:
-rw-r--r--

And the Game.ini content:
https://pastebin.com/xaT5u01j

**Comment by mschnitzer** [comment]
So the damage values are being displayed by setting `ShowFloatingDamageText=true` in the `GameUserSettings.ini`, not in `Game.ini`. However, in your `Game.ini`, I don't see this setting, so it appears to me that you have not set it at all.

Furthermore, can you please explain how you restarted your server and also who owns that file? Is it `root:root` or `25000:25000` ?

**Comment by Powershooter83** [comment]
Ohh, sorry I really thought that had to be adjusted in Game.ini. The Game.ini file belongs to root root and I restarted the server with `docker-compose restart asa-server-1`

**Comment by mschnitzer** [comment]
Could you please use `docker-compose up -d` and check whether it is still owned by `root:root` ?

Did you test any other changes whether they are working?

**Comment by Powershooter83** [comment]
After compose -d it is now 2500 : 2500. I haven't really tested the settings otherwise, I'll give it a try tonight.

**Comment by Powershooter83** [comment]
To be honest, the fault could now also lie with me. (I thought Game.ini would have more influence, e.g. Tamingspeed, but I've just seen that this is done in the UserSettings)

So this issue could be closed,
thanks for the detailed help :D

**Comment by mschnitzer** [comment]
I'm glad I could help you. Feel free to open another issue if you have any further issues.
