### ISSUE TITLE
Adding Mods

### ISSUE THREAD

**Issue by njakes** [mschnitzer/ark-survival-ascended-linux-container-image#21]
Is it possible to add mods via environment variable with MOD_IDS?

**Comment by mschnitzer** [comment]
Yes, you can add mods, but they need to be put behind `ASA_START_PARAMS` like so:

```
ASA_START_PARAMS=TheIsland_WP?listen?Port=7777?RCONPort=27020?RCONEnabled=True -WinLiveMaxPlayers=50 -mods=123,456,789
```

It automatically downloads all pending mods, so it might take a while until all mods have been downloaded.

There's a plan to make this process a little easier, but this is not yet released as an implementation in `asa-ctrl` yet ( see #7 )

**Comment by mschnitzer** [comment]
@njakes since you gave my reply a like, were you able to install mods?

**Comment by njakes** [comment]
I haven't tried yet but will report back when I do.

**Comment by heusmich** [comment]
> Yes, you can add mods, but they need to be put behind `ASA_START_PARAMS` like so:
> 
> ```
> ASA_START_PARAMS=TheIsland_WP?listen?Port=7777?RCONPort=27020?RCONEnabled=True -WinLiveMaxPlayers=50 -mods=123,456,789
> ```
> 
> It automatically downloads all pending mods, so it might take a while until all mods have been downloaded.
> 
> There's a plan to make this process a little easier, but this is not yet released as an implementation in `asa-ctrl` yet ( see #7 )

Hi,
For me this is not working. I added the mod IDs in the start parameters but they will not be loaded. My server is still without any mods. So currently the start parameters line in the docker-compose.yml file looks like this:

**environment:
      - ASA_START_PARAMS=TheIsland_WP?listen?Port=27015?RCONPort=27020?RCONEnabled=True -WinLiveMaxPlayers=10 -mods=929110,929785,928988,932331**

Is there anything more that has to be done besides adding the mods to the start parameters?
I already tried to add the mod IDs also to the GameUserSettings.ini as entry "ActiveMods=123,456,..." but it´s also not working.
Would be nice if you could help me with that.
In general the server is working and we can play on it.

Best regards
heusmich

**Comment by heusmich** [comment]
OK, I think I found the problem.

I always restarted my server with the command **docker-compose restart asa-server-1**.
But it seems that everytime a change was made in the start parameters, the container has to be recreated with the command **docker-compose up -d**.

**Comment by mschnitzer** [comment]
Yes, you need to use `docker-compose up -d`. Using your three mods, I was able to launch my test server successfully and it downloaded all mods. Any other change besides `-mods` is not needed.

I'm glad it's working for you.

**Comment by heusmich** [comment]
One additional question.
When I change the start parameters, I have to use the **docker-compose up -d** command.
Which command do I have to use when I change settings in Game.ini or GameUserSettings.ini? Is the command **docker-compose restart asa-server-1** OK or do I also have to use the **docker-compose up -d** command?

**Comment by mschnitzer** [comment]
`up -d` recreates the container if the `docker-compose.yml` file has changed. In your case, where you want to edit the game config files, you can do a simple `docker-compose restart asa-server-1`.

**Comment by mschnitzer** [comment]
I'm closing this issue, as there's no response from the issue creator yet. If it's not working, please reopen this issue.
