### ISSUE TITLE
Svartlfheim map

### ISSUE THREAD

**Issue by DarkVentHead** [mschnitzer/ark-survival-ascended-linux-container-image#25]
With the proper Svartlfheim_WP (replacing TheIsland_WP and the proper -mods=893657 called at the end of ASA_SERVER_PARAMS. The container will hang after loading. 

If you simply just leave the mod callout the container WILL NOT HANG and will show in server browser and require the mod be downloaded (albeit displaying the island as the map that is being played) but the connection will timeout. removing mod callout and putting TheIsland_WP back in place. The server launches and starts and connects with no issues. 

I only bring this up as an issue as i'm wondering if this container setup IS ALLOWED to run different maps?

**Comment by mschnitzer** [comment]
I just tested it on my development server with a fresh ASA server installation and I cannot reproduce it:

My start parameters:
```
Svartalfheim_WP?listen?Port=7777?RCONPort=27020?RCONEnabled=True -WinLiveMaxPlayers=50 -mods=893657
```

I guess you just need to wait a little longer. I was waiting some time, as I had to download the map as well when joining the server.
