### ISSUE TITLE
Dockerfile source

### ISSUE THREAD

**Issue by allenpetersen** [mschnitzer/ark-survival-ascended-linux-container-image#30]
Could you provide the source Dockerfile for `mschnitzer/asa-linux-server` please? I would like to inspect what I'm running. I don't understand what is happening with the single "KIWI 9.24.43" layer.

**Comment by mschnitzer** [comment]
There's no dockerfile, the image is built with `kiwi-ng`:

* https://osinside.github.io/kiwi/
* https://github.com/OSInside/kiwi

If you prefer building your own image instead of relying on my pre-built image, you need to install `kiwi-ng` and run my Makefile.

**Comment by mschnitzer** [comment]
Adding more context:

kiwi is a tool that allows you to images in several formats (e.g. qcow2, oci container images, iso, etc.) based on one image description ([click](https://github.com/mschnitzer/ark-survival-ascended-linux-container-image/blob/main/appliance.kiwi)). This profile describes what packages are being installed inside the container and during bootstrapping. Once the image is ready, there's a config bash script running at the end of the build process that allows for modifications on the file system level inside of the image ([click](https://github.com/mschnitzer/ark-survival-ascended-linux-container-image/blob/main/config.sh)).

This is how the container image is being built, it's an alternative way to build a container image.

**Comment by mschnitzer** [comment]
@allenpetersen has your question been answered?

**Comment by mschnitzer** [comment]
Please reopen if you have any further questions.
