### ISSUE TITLE
"Cluster" configuration?

### ISSUE THREAD

**Issue by Romaq** [mschnitzer/ark-survival-ascended-linux-container-image#31]
"At some point" I would like to set up a cluster between The Island and https://ark.wiki.gg/wiki/Mod:Svartalfheim. Would anyone have a "cook-book" for having asa-server-1 and asa-server-2 communicate to allow survivors, dinos, and materials go between the two? I'm not really clear if this is even enabled in the software just yet since The Island is the only "official" map out. When I attempted this for ASE, I had to have a directory both maps shared to store relevant data to go between the two. This option may be a "hard no" at this time, and that's cool. I'm just clueless on how to approach the issue.

**Comment by mschnitzer** [comment]
My understanding is, that cluster support is not in ASA yet and they plan to introduce it once the next official map is released. If you heard news that this is already working, please provide me with the source so that I can look into it.

**Comment by Romaq** [comment]
Thank you. I really was *NOT* clear on this. What you said was my impression, and I couldn't recall from where to point to anything. I expect this to be a hot topic once clustering is officially open. :)

**Comment by mschnitzer** [comment]
That's fine. Once you heard anything about cluster support, feel free to create an issue to request this as a feature.
