### ISSUE TITLE
Server not visible in Serverlist anymore?

### ISSUE THREAD

**Issue by DopiGFX** [mschnitzer/ark-survival-ascended-linux-container-image#34]
Hey,
scince the update around two days ago, I cannot find my server in the serverlist anymore. 
I restarted it multiple times and also recreated the container but nothing seems to work. 
Is there a way to check the version of the server? The first restart after the update posted "Downloading update" in the logs, so I'd say it has installed the latest version.

For some reason the solution for joining with the "open $IP:$PORT" command doesn't work either. I have set a password for my server and googled for the command pattern using a password. I found out it has to be like that: "open $IP:$PORT?$PASSWORD". Maybe I'm doing something wrong, but it always tells me "Invalid Password" when trying to join like that.

Any ideas? 

Kind Regards

**Comment by DopiGFX** [comment]
Here's the log from the first restart after the update came out

![image](https://github.com/mschnitzer/ark-survival-ascended-linux-container-image/assets/67605541/a959797f-342b-4618-8b18-06c7b4978afc)
![image](https://github.com/mschnitzer/ark-survival-ascended-linux-container-image/assets/67605541/ab5c30a7-6bb0-4066-b79d-2528c3d989c5)

**Comment by mschnitzer** [comment]
So the "installing update..." lines are `steamcmd` related and not ARK related. What matters is the "Update state (0x61)" which indicate that the server is downloading an update. When you trigger a restart of the container, the server calls `steamcmd` to apply any publicly visible updates from Wildcard.

https://steamdb.info/app/2430930/depots/

The last update in the `public` branch was released 5 hours ago, I'd recommend restarting again and wait ~10 minutes for the server to show up. Also make sure that your client is not consuming from the `public_test_realm` branch which was recently launched to avoid any issues with incompatible versions.

The version the server launches can be verified by running `docker exec -t asa-server-1 cat server-files/ShooterGame/Saved/Logs/ShooterGame.log`.

There should be a line like this:
```
[2023.12.14-03.00.55:490][  0]ARK Version: 32.21
```

If that line is not there yet, the server might still be booting up.

**Comment by mschnitzer** [comment]
I just realized they added a new filter option in the server browser that is disabled by default, it is called something like "Show player servers" and can be found on the bottom right of the server browser list. By default only Nitrado servers seem to be shown and private dedicated servers will only be shown once this option is checked. Looks like this is a new "feature" if you want to call it that way.

**Comment by DopiGFX** [comment]
Ahh dang, this little checkbox was the issue.... definitely a "feature" that no one needs -.-

I think that would fit into this area in the future: https://github.com/mschnitzer/ark-survival-ascended-linux-container-image?tab=readme-ov-file#addressing-connection-timeout-issues

Thanks for your quick and detailed answer! 🙏
