### ISSUE TITLE
After Update Server is not showing

### ISSUE THREAD

**Issue by granatelbart** [mschnitzer/ark-survival-ascended-linux-container-image#35]
After install Ark update the newest 32.24 the gameserver is not anymore showing on the gameserverlist

**Comment by guiever** [comment]
Same here, I can replicate the issue.

**Comment by crisstrance** [comment]
I have the same problem! any news?

**Comment by heusmich** [comment]
The same for me, I hope that there will be a fix soon...

**Comment by mschnitzer** [comment]
The solution is here, they introduced a new "feature" for people not hosting their server on Nitrado:
https://github.com/mschnitzer/ark-survival-ascended-linux-container-image/issues/34#issuecomment-1857228984

**Comment by guiever** [comment]
> The solution is here, they introduced a new "feature" for people not hosting their server on Nitrado: [#34 (comment)](https://github.com/mschnitzer/ark-survival-ascended-linux-container-image/issues/34#issuecomment-1857228984)

I don't think its the same issue, I check the box and my server is still not showing.

**Comment by heusmich** [comment]
> The solution is here, they introduced a new "feature" for people not hosting their server on Nitrado: [#34 (comment)](https://github.com/mschnitzer/ark-survival-ascended-linux-container-image/issues/34#issuecomment-1857228984)

This worked for me, thx!

**Comment by guiever** [comment]
Me too, thanks!

**Comment by granatelbart** [comment]
nice guys worked
