### ISSUE TITLE
How to use the image with Proton?

### ISSUE THREAD

**Issue by jerome80** [mschnitzer/ark-survival-ascended-linux-container-image#36]
how to launch with Proton thank
![proton](https://github.com/mschnitzer/ark-survival-ascended-linux-container-image/assets/32602783/c15326fe-49d5-4904-b550-aefea065e1d0)

**Comment by mschnitzer** [comment]
I never used Proton before, sorry. You have to figure it out yourself or wait for someone that has knowledge in that area. Otherwise just follow my guide in the README.
