### ISSUE TITLE
is this importand?

### ISSUE THREAD

**Issue by kg5hfl** [mschnitzer/ark-survival-ascended-linux-container-image#39]
will this error be an issue?

Failed to read /etc/machine-id, error Invalid argument.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely

Thanks. Great work BTW.

**Comment by mschnitzer** [comment]
This does not have any effect on the functionality of your Game Server, feel free to ignore this.

**Comment by mschnitzer** [comment]
Please reopen if you have any further questions.

**Comment by kg5hfl** [comment]
Thanks for the reply and your work on this project. Super great
instructions. Worked the 2nd time only because I didn't follow the docker
instructions to begin with... 🤓
