### ISSUE TITLE
Sorry to bother

### ISSUE THREAD

**Issue by kg5hfl** [mschnitzer/ark-survival-ascended-linux-container-image#42]
Any way to get the RCON command 'getgamelog' to work. i keep getting 'Server Received, But no Response.'

thanks in advance.

Update state (0x5) verifying install, progress: 51.69 (4850494221 / 9382920526)
 Update state (0x5) verifying install, progress: 57.69 (5412543524 / 9382920526)
 Update state (0x5) verifying install, progress: 63.76 (5982249144 / 9382920526)
 Update state (0x5) verifying install, progress: 69.75 (6544285880 / 9382920526)
 Update state (0x5) verifying install, progress: 75.74 (7106322616 / 9382920526)
 Update state (0x5) verifying install, progress: 81.71 (7666842063 / 9382920526)
 Update state (0x5) verifying install, progress: 87.69 (8228266431 / 9382920526)
 Update state (0x5) verifying install, progress: 93.76 (8797526479 / 9382920526)
 Update state (0x5) verifying install, progress: 99.76 (9360447951 / 9382920526)
Success! App '2430930' fully installed.
Starting the ARK: Survival Ascended dedicated server...
Start parameters: TheIsland_WP?listen?Port=7777?RCONPort=27020?RCONEnabled=True -servergamelog -WinLiveMaxPlayers=26 -Mods=928621,929420,928501,941461,927090,932976 -NoBattlEye
esync: up and running.
Failed to read /etc/machine-id, error Invalid argument.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
^C
kg5hfl@gameserver:~/asa-server$ sudo docker exec -t asa-server-1 asa-ctrl rcon --exec 'GetGameLog'
Server received, But no response!!

kg5hfl@gameserver:~/asa-server$ sudo docker exec -t asa-server-1 asa-ctrl rcon --exec GetGameLog
Server received, But no response!!

kg5hfl@gameserver:~/asa-server$

**Comment by mschnitzer** [comment]
Same on my server, not sure if this is an ASA specific issue or a config option needs to be set first. There are some topics on Google on this one, but I couldn't find any definitive answer.

But instead of using RCON, you could just query the logs like this:
```
docker exec -t asa-server-1 cat server-files/ShooterGame/Saved/Logs/ShooterGame.log
```

**Comment by grant4790** [comment]
I went in a manually added a machine ID to my container, by using this 

# cat /sys/class/dmi/id/board_serial > /etc/machine-id
asa-server-1:/home/gameserver # cat /etc/machine-id

now my log for my container are just the wine error

IDK if this is helpful or not but its something 

-- type 'quit' to exit --
Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
OK

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
 Update state (0x5) verifying install, progress: 0.09 (8254464 / 9382920526)
 Update state (0x5) verifying install, progress: 6.39 (599381650 / 9382920526)
 Update state (0x5) verifying install, progress: 12.80 (1201264274 / 9382920526)
 Update state (0x5) verifying install, progress: 19.30 (1810486930 / 9382920526)
 Update state (0x5) verifying install, progress: 25.78 (2419010585 / 9382920526)
 Update state (0x5) verifying install, progress: 32.27 (3028204197 / 9382920526)
 Update state (0x5) verifying install, progress: 38.69 (3630147773 / 9382920526)
 Update state (0x5) verifying install, progress: 45.18 (4239617293 / 9382920526)
 Update state (0x5) verifying install, progress: 51.69 (4849888525 / 9382920526)
 Update state (0x5) verifying install, progress: 58.10 (5451783716 / 9382920526)
 Update state (0x5) verifying install, progress: 64.60 (6061335224 / 9382920526)
 Update state (0x5) verifying install, progress: 71.10 (6671606456 / 9382920526)
 Update state (0x5) verifying install, progress: 77.60 (7280829112 / 9382920526)
 Update state (0x5) verifying install, progress: 84.01 (7882750943 / 9382920526)
 Update state (0x5) verifying install, progress: 90.51 (8492434383 / 9382920526)
 Update state (0x5) verifying install, progress: 97.00 (9101767647 / 9382920526)
Success! App '2430930' fully installed.
Starting the ARK: Survival Ascended dedicated server...
Start parameters: TheIsland_WP?SessionName=HereWeGoAgainDox?listen?Port=7777?RCONPort=27020?RCONEnabled=True -WinLiveMaxPlayers=10 -mods=929912,951374,928597,928621,947033
,945883,930494,929785
esync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely

**Comment by kg5hfl** [comment]
I did sudo tail - f and that works good too. Thanks for the help.

**Comment by mschnitzer** [comment]
Alright, please reopen if you have any further questions.

**Comment by kg5hfl** [comment]
Any idea how to change the time in the container? I've tried several methods with no luck.
