### ISSUE TITLE
I am unsure of what I am doing wrong, sorry if this is the wrong place for this

### ISSUE THREAD

**Issue by grant4790** [mschnitzer/ark-survival-ascended-linux-container-image#43]
root@grantubuntu:~/asa-server# docker logs -f asa-server-1
Redirecting stderr to '/home/gameserver/Steam/logs/stderr.txt'
Logging directory: '/home/gameserver/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1702079268
-- type 'quit' to exit --
Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
OK

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
 Update state (0x5) verifying install, progress: 0.08 (7340032 / 9382920526)
 Update state (0x5) verifying install, progress: 5.81 (545002130 / 9382920526)
 Update state (0x5) verifying install, progress: 12.30 (1154224786 / 9382920526)
 Update state (0x5) verifying install, progress: 18.79 (1763447442 / 9382920526)
 Update state (0x5) verifying install, progress: 25.28 (2371971097 / 9382920526)
 Update state (0x5) verifying install, progress: 31.69 (2973824677 / 9382920526)
 Update state (0x5) verifying install, progress: 38.19 (3583108285 / 9382920526)
 Update state (0x5) verifying install, progress: 44.68 (4192577805 / 9382920526)
 Update state (0x5) verifying install, progress: 51.10 (4794460429 / 9382920526)
 Update state (0x5) verifying install, progress: 57.59 (5403695652 / 9382920526)
 Update state (0x5) verifying install, progress: 64.09 (6013247160 / 9382920526)
 Update state (0x5) verifying install, progress: 70.58 (6622469816 / 9382920526)
 Update state (0x5) verifying install, progress: 77.01 (7225401016 / 9382920526)
 Update state (0x5) verifying install, progress: 83.49 (7833857999 / 9382920526)
 Update state (0x5) verifying install, progress: 89.99 (8443355087 / 9382920526)
 Update state (0x5) verifying install, progress: 96.41 (9046018015 / 9382920526)
Success! App '2430930' fully installed.
Starting the ARK: Survival Ascended dedicated server...
Start parameters: TheIsland_WP?listen?Port=7777?RCONPort=27020?RCONEnabled=True -WinLiveMaxPlayers=10 -mods=929912,951374,928597,928621,947033,945883,930494,929785 -NoBattleEte
esync: up and running.
Failed to read /etc/machine-id, error Invalid argument.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely

  GNU nano 6.2                                                                          docker-compose.yml
version: "3.3"
services:
  asa-server-1:
    container_name: asa-server-1
    hostname: asa-server-1
    entrypoint: "/usr/bin/start_server"
    user: gameserver
    image: "mschnitzer/asa-linux-server:latest"
    environment:
      - ASA_START_PARAMS=TheIsland_WP?listen?Port=7777?RCONPort=27020?RCONEnabled=True -WinLiveMaxPlayers=10 -mods=929912,951374,928597,928621,947033,945883,930494,929785 -NoBattleEte
      - ENABLE_DEBUG=0
    ports:
      # Game port for player connections through the server browser
      - 192.168.1.11:7777:7777/udp
      # RCON port for remote server administration
      - 192.168.1.11:27020:27020/tcp
    depends_on:
      - set-permissions-1
    volumes:
      - steam-1:/home/gameserver/Steam:rw
      - steamcmd-1:/home/gameserver/steamcmd:rw
      - server-files-1:/home/gameserver/server-files:rw
    networks:
      asa-network:
  set-permissions-1:
    entrypoint: "/bin/bash -c 'chown -R 25000:25000 /steam ; chown -R 25000:25000 /steamcmd ; chown -R 25000:25000 /server-files'"
    user: root
    image: "opensuse/leap"
    volumes:
      - steam-1:/steam:rw
      - steamcmd-1:/steamcmd:rw
      - server-files-1:/server-files:rw
#  asa-server-2:
#    container_name: asa-server-2
#    hostname: asa-server-2
#    entrypoint: "/usr/bin/start_server"
#    user: gameserver
#    image: "mschnitzer/asa-linux-server:latest"
#    environment:
#      - ASA_START_PARAMS=TheIsland_WP?listen?Port=7778?RCONPort=27021?RCONEnabled=True -WinLiveMaxPlayers=50
#    ports:
#      # Game port for player connections through the server browser
#      - 0.0.0.0:7778:7778/udp
#      # RCON port for remote server administration
#      - 0.0.0.0:27021:27021/tcp
#    depends_on:
#      - set-permissions-2
#    volumes:
#      - steam-2:/home/gameserver/Steam:rw
#      - steamcmd-2:/home/gameserver/steamcmd:rw
#      - server-files-2:/home/gameserver/server-files:rw
#    networks:
#      asa-network:
#  set-permissions-2:
#    entrypoint: "/bin/bash -c 'chown -R 25000:25000 /steam ; chown -R 25000:25000 /steamcmd ; chown -R 25000:25000 /server-files'"
#    user: root
#    image: "opensuse/leap"
#    volumes:
#      - steam-2:/steam:rw
#      - steamcmd-2:/steamcmd:rw
#      - server-files-2:/server-files:rw
volumes:
  steam-1:
  steamcmd-1:
  server-files-1:
#  steam-2:
#  steamcmd-2:
#  server-files-2:
networks:
  asa-network:
    attachable: true
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: 'asanet'

**Comment by grant4790** [comment]
![erro](https://github.com/mschnitzer/ark-survival-ascended-linux-container-image/assets/103959037/1f7f6b45-d45b-4f4c-b2de-1dc003ae389b)
This is what I am getting when i use the open command in game

**Comment by grant4790** [comment]
Update again I got in with the open command issue with that was my lack of an ability to spell battleye but it is no visable in the server browser, also with the open command how do i add a server password to that. 

Thank you  for reading and helping this in advanced I am not the most skilled with linux I really only use it for this

**Comment by mschnitzer** [comment]
Not sure how to use a password with `open`, but I heard it is possible, you might need to google a bit. IIRC there was also someone commenting in an issue how this works, but I do not remember exactly which issue it was.

If the server is not showing up, this is very likely due to Wildcard changing what servers are shown by default. Did you check the checkbox on the bottom right of the server browser that says "Show player servers"? By default, only servers from Nitrado are shown.

**Comment by grant4790** [comment]
okay thanks for the update on the open command, I will do some more digging, I ended up just turning passwords off for a little bit and my friends were able to connect via my public ip and port. but yeah I had all the little boxes down there checked in the server browser

**Comment by mschnitzer** [comment]
Are you hosting the server in a home environment?

**Comment by grant4790** [comment]
Yes I am,
Ubuntu 22 server LTS
Ryzen 5 4600G
32 DDR4

**Comment by mschnitzer** [comment]
I'm not sure what causes the server to not appear. I'd like to give it a try myself, could you please start the server and let me know the server name? You can also send me a mail if you don't want to share the server name here. My mail is on my GitHub profile.

**Comment by mschnitzer** [comment]
Haven't received any mail from you so far, is this still an issue for you or can we close it?

**Comment by grant4790** [comment]
I thought I sent it last week let me double check and re send. Sorry I didn’t let you know missed that part of the last email

**Comment by grant4790** [comment]
My bad I never sent it. My apologies let me get you that info now

**Comment by grant4790** [comment]
Okay sent the email this time

**Comment by mschnitzer** [comment]
I received your mail and found your server on the server list. Please double check that you have the same checkboxes checked like me:

![server](https://github.com/mschnitzer/ark-survival-ascended-linux-container-image/assets/8287131/5311f444-f4de-49d7-9454-462d39d152ed)

I censored the name of your server, but I can share the uncensored screen with you if you want.

**Comment by grant4790** [comment]
Mm interesting, I will check that when I return home I had the middle two boxes checked las well on my end so maybe that was why.

Thanks

From Grant Peer
________________________________

**Comment by mschnitzer** [comment]
Yea, I'd suggest to give it another try and report back if that still doesn't work.

**Comment by grant4790** [comment]
Okay I found it this time odd it wasnt appearing before

**Comment by mschnitzer** [comment]
Could be that your client or server had different versions or it took longer that the server appears. Anyway, I'm glad this has been resolved.

**Comment by grant4790** [comment]
Yes me too thanks

From Grant Peer
________________________________
