### ISSUE TITLE
time is Off

### ISSUE THREAD

**Issue by kg5hfl** [mschnitzer/ark-survival-ascended-linux-container-image#44]
Tried to change time with date -s inside the container, but it says Operation Not Permitted. Any suggestions on changing or syncing with local time?

**Comment by mschnitzer** [comment]
I developed a fix for this issue. I hope this works on all distributions seamlessly. Once I release 1.3.0 of this container image, you can adjust your `docker-compose.yml` and add the following line to your volume list:

https://github.com/mschnitzer/ark-survival-ascended-linux-container-image/commit/426f8f2cca5452c8aac98e7863cde96c6e2b1749#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3R24

I will release 1.3.0 either today or tomorrow.
