### ISSUE TITLE
Can't see the server

### ISSUE THREAD

**Issue by Shanpapa** [mschnitzer/ark-survival-ascended-linux-container-image#45]
Hi, I followed your guide step by step, waited for about 30 minutes, and still can't see the server for some reason. Any suggestions, please?
Renting a dedicated server from Hetzner, and never did anything like this before.
If you need any other details please let me know. 
Thanks

Success! App '2430930' fully installed.
Starting the ARK: Survival Ascended dedicated server...
Start parameters: TheIsland_WP?listen?Port=7777?RCONPort=27020?RCONEnabled=True -WinLiveMaxPlayers=50
Proton: Upgrading prefix from None to GE-Proton8-21 (/home/gameserver/server-files/steamapps/compatdata/2430930/)
fsync: up and running.
Failed to read /etc/machine-id, error Invalid argument.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
root@Debian-bookworm-latest-amd64-base ~/asa-server # docker exec asa-server-1 cat server-files/ShooterGame/Saved/Config/WindowsServer/GameUserSettings.ini | grep SessionName
SessionName=ARK #674154

**Comment by mschnitzer** [comment]
Make sure to thave 'Show player servers' checked in the bottom right of your server browser. Then refresh the server list.

**Comment by Shanpapa** [comment]
Shame on me, Thanks

**Comment by mschnitzer** [comment]
No worries, that's not really obvious if you are not following patch notes.
