### ISSUE TITLE
Container stops with exit code 29 

### ISSUE THREAD

**Issue by Movexcreations** [mschnitzer/ark-survival-ascended-linux-container-image#46]
Fresh install of Ubuntu 22.04.3 LTS
Lightweight package with no other software other than TeamViewer installed

Container starts but within 1min stops with exit code 29

I have not modified the .yaml in anyway

root@mediapc:/home/billy/asa-server# docker inspect asa-server-1 | grep Exit
            "ExitCode": 29,
root@mediapc:/home/billy/asa-server# ^C
root@mediapc:/home/billy/asa-server# docker logs -f asa-server-1
--2024-02-03 01:20:19--  https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
Resolving steamcdn-a.akamaihd.net (steamcdn-a.akamaihd.net)... 123.253.149.154, 123.253.149.155
Connecting to steamcdn-a.akamaihd.net (steamcdn-a.akamaihd.net)|123.253.149.154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2428561 (2.3M) [application/octet-stream]
Saving to: 'steamcmd_linux.tar.gz'

     0K .......... .......... .......... .......... ..........  2% 3.47M 1s
  2300K .......... .......... .......... .......... .......... 99% 34.9M 0s
  2350K .......... .......... .                               100% 64.8M=0.2s

2024-02-03 01:20:19 (9.65 MB/s) - 'steamcmd_linux.tar.gz' saved [2428561/2428561]

steamcmd.sh
linux32/steamcmd
linux32/steamerrorreporter
linux32/libstdc++.so.6
linux32/crashhandler.so
Redirecting stderr to '/home/gameserver/Steam/logs/stderr.txt'
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
[  0%] Checking for available update...

[100%] Downloading update (59782 of 59782 KB)...
[100%] Download Complete.
[----] Applying update...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Cleaning up...
[----] Update complete, launching...
tid(26) burning pthread_key_t == 0 so we never use it
Redirecting stderr to '/home/gameserver/Steam/logs/stderr.txt'
Logging directory: '/home/gameserver/Steam/logs'
/tmp/dumps insufficient permissions - delete and recreate
[  0%] Checking for available updates...
[----] Verifying installation...
[  0%] Downloading update...
[  0%] Checking for available updates...
[----] Download complete.
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Cleaning up...
[----] Update complete, launching Steamcmd...
tid(38) burning pthread_key_t == 0 so we never use it
Redirecting stderr to '/home/gameserver/Steam/logs/stderr.txt'
Logging directory: '/home/gameserver/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1705108307
-- type 'quit' to exit --
Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
OK

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x81) verifying update, progress: 0.53 (50796336 / 9503732066)
 Update state (0x81) verifying update, progress: 97.24 (9241109843 / 9503732066)
Success! App '2430930' fully installed.
Starting the ARK: Survival Ascended dedicated server...
Start parameters: TheIsland_WP?listen?Port=7777?RCONPort=27020?RCONEnabled=True -WinLiveMaxPlayers=50 
Proton: Upgrading prefix from None to GE-Proton8-21 (/home/gameserver/server-files/steamapps/compatdata/2430930/)
esync: up and running.
Failed to read /etc/machine-id, error Invalid argument.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
tid(11) burning pthread_key_t == 0 so we never use it
Redirecting stderr to '/home/gameserver/Steam/logs/stderr.txt'
Logging directory: '/home/gameserver/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1705108307
-- type 'quit' to exit --
Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
OK

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x5) verifying install, progress: 3.72 (353277996 / 9503732066)
 Update state (0x5) verifying install, progress: 97.00 (9218797603 / 9503732066)
Success! App '2430930' fully installed.
Starting the ARK: Survival Ascended dedicated server...
Start parameters: TheIsland_WP?listen?Port=7777?RCONPort=27020?RCONEnabled=True -WinLiveMaxPlayers=50 
esync: up and running.
Failed to read /etc/machine-id, error Invalid argument.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
tid(11) burning pthread_key_t == 0 so we never use it
Redirecting stderr to '/home/gameserver/Steam/logs/stderr.txt'
Logging directory: '/home/gameserver/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1705108307
-- type 'quit' to exit --
Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
OK

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x5) verifying install, progress: 2.32 (220364259 / 9503732066)
 Update state (0x5) verifying install, progress: 99.89 (9493185898 / 9503732066)
Success! App '2430930' fully installed.
Starting the ARK: Survival Ascended dedicated server...
Start parameters: TheIsland_WP?listen?Port=7777?RCONPort=27020?RCONEnabled=True -WinLiveMaxPlayers=50 
esync: up and running.
Failed to read /etc/machine-id, error Invalid argument.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
tid(11) burning pthread_key_t == 0 so we never use it
Redirecting stderr to '/home/gameserver/Steam/logs/stderr.txt'
Logging directory: '/home/gameserver/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1705108307
-- type 'quit' to exit --
Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
OK

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x5) verifying install, progress: 1.90 (180113408 / 9503732066)
 Update state (0x5) verifying install, progress: 98.24 (9336238115 / 9503732066)
Success! App '2430930' fully installed.
Starting the ARK: Survival Ascended dedicated server...
Start parameters: TheIsland_WP?listen?Port=7777?RCONPort=27020?RCONEnabled=True -WinLiveMaxPlayers=50 
esync: up and running.
Failed to read /etc/machine-id, error Invalid argument.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely

root@mediapc:/home/billy/asa-server# docker ps -a
CONTAINER ID   IMAGE                                COMMAND                  CREATED          STATUS                       PORTS     NAMES
2eb66b0e3b31   mschnitzer/asa-linux-server:latest   "/usr/bin/start_serv…"   55 minutes ago   Exited (29) 20 minutes ago             asa-server-1
485edd050820   opensuse/leap                        "/bin/bash -c 'chown…"   55 minutes ago   Exited (0) 22 minutes ago              asa-server_set-permissions-1_1

**Comment by mschnitzer** [comment]
Are you using Proxmox or any virtualization?

**Comment by Movexcreations** [comment]
No, standard Ubuntu install with no added virtualisation or software of any kind other than Team Viewer which I use to access it.

**Comment by mschnitzer** [comment]
What are the specs of your server? CPU, RAM, Disk Space?

**Comment by Movexcreations** [comment]
CPU AMD® Phenom(tm) ii x6 1035t
24G RAM
1TB drive, 900G remaining

**Comment by mschnitzer** [comment]
The processor is fairly old, not sure if it's capable of running an ASA server tbh, I'd give it a try with newer hardware.

Is it a physical machine at your home?

**Comment by Movexcreations** [comment]
It is a physical machine at home and it could be the hardware but I don't believe theres any real way to confirm that other than our suspicions.... Prior to trying this Docker Container I attempted to run in on Windows 10 on the same system. Similar scenario, the .exe doesn't run, no error or any response of any kind it just doesn't do anything.... So with that result I installed Ubuntu and thought I'd try a container that had a working environment.

**Comment by mschnitzer** [comment]
Did you try it on another machine or have you solved your issue?

**Comment by mschnitzer** [comment]
Please reopen if this is still an issue.
