### ISSUE TITLE
How to delete the current savegame

### ISSUE THREAD

**Issue by heusmich** [mschnitzer/ark-survival-ascended-linux-container-image#47]
Hi,

I want to reset the map to defaults, delete the players, structures and so on and delete the current savegame.
Can you tell me which files / folders have to be deleted to do this?
Maybe delete the folder "/var/lib/docker/volumes/asa-server_server-files-1/_data/ShooterGame/Saved/SavedArks/TheIsland_WP" and all files in this folder or do I have to delete other files / folders?

Thanks and best regards
heusmich

**Comment by mschnitzer** [comment]
Deleting `TheIsland_WP` in `ShooterGame/Saved/SavedArks` is working just fine.

**Comment by heusmich** [comment]
OK nice, thanks for the info.

**Comment by mschnitzer** [comment]
You're welcome, please reopen if you have any further questions on this.
