### ISSUE TITLE
docker exec -t asa-server-1 asa-ctrl rcon --exec 'saveworld' error?

### ISSUE THREAD

**Issue by NRmash** [mschnitzer/ark-survival-ascended-linux-container-image#49]
Hey,

When I enter the command "docker exec -t asa-server-1 asa-ctrl rcon --exec 'saveworld'" the following error message appears:

asa@nastyroots:~$ sudo docker exec -t asa-server-1 asa-ctrl rcon --exec 'saveworld'
/usr/lib64/ruby/gems/3.3.0+0/gems/iniparse-1.5.0/lib/iniparse.rb:39:in `gsub': invalid byte sequence in US-ASCII (ArgumentError)

    IniParse::Parser.new(source.gsub(/(?<!\\)\\\n/, '')).parse
                                     ^^^^^^^^^^^^^^^^^
        from /usr/lib64/ruby/gems/3.3.0+0/gems/iniparse-1.5.0/lib/iniparse.rb:39:in `parse'
        from /usr/share/asa-ctrl/helpers/ini_config_helper.rb:14:in `parse'
        from /usr/share/asa-ctrl/helpers/ini_config_helper.rb:4:in `game_user_settings_ini'
        from /usr/share/asa-ctrl/rcon/rcon.rb:53:in `identify_password'
        from /usr/share/asa-ctrl/cli/interfaces/rcon_interface.rb:20:in `run_command!'
        from /usr/share/asa-ctrl/cli/interfaces/rcon_interface.rb:12:in `execute!'
        from /usr/share/asa-ctrl/cli/interfaces/rcon_interface.rb:7:in `initialize'
        from /usr/bin/asa-ctrl:28:in `new'
        from /usr/bin/asa-ctrl:28:in `block (2 levels) in <main>'
        from /usr/lib64/ruby/gems/3.3.0+0/gems/slop-4.10.1/lib/slop/option.rb:66:in `ensure_call'
        from /usr/lib64/ruby/gems/3.3.0+0/gems/slop-4.10.1/lib/slop/parser.rb:117:in `process'
        from /usr/lib64/ruby/gems/3.3.0+0/gems/slop-4.10.1/lib/slop/parser.rb:124:in `try_process'
        from /usr/lib64/ruby/gems/3.3.0+0/gems/slop-4.10.1/lib/slop/parser.rb:59:in `block in parse'
        from /usr/lib64/ruby/gems/3.3.0+0/gems/slop-4.10.1/lib/slop/parser.rb:49:in `each'
        from /usr/lib64/ruby/gems/3.3.0+0/gems/slop-4.10.1/lib/slop/parser.rb:49:in `each_with_index'
        from /usr/lib64/ruby/gems/3.3.0+0/gems/slop-4.10.1/lib/slop/parser.rb:49:in `parse'
        from /usr/lib64/ruby/gems/3.3.0+0/gems/slop-4.10.1/lib/slop/options.rb:76:in `parse'
        from /usr/lib64/ruby/gems/3.3.0+0/gems/slop-4.10.1/lib/slop.rb:23:in `parse'
        from /usr/bin/asa-ctrl:21:in `<main>'

**Comment by NRmash** [comment]
I have found out what the problem was.
No umlauts (äüöß) may be used in the GUS.ini entry "Message=".
I replaced them and now everything works as it should :)
Thanks for the hint, that's why I tested it :D

**Comment by mschnitzer** [comment]
Thanks for the feedback!
