### ISSUE TITLE
Server info?

### ISSUE THREAD

**Issue by NRmash** [mschnitzer/ark-survival-ascended-linux-container-image#52]
Hey, is there a way to read information from a server?
How many players are on it, the names etc.?
Something like: docker exec -t asa-server-01 asa-ctrl rcon --exec 'info' ?

Thank you very much :)

**Comment by mschnitzer** [comment]
I believe `listplayers`. In general you can enter any RCON command that is available for ASE in ASA.

This probably not an exhaustive list of all RCON commands:
https://www.ark-survival.net/de/2015/06/08/konsolenbefehle-cheatbefehle/

The site's German, but you can use google translate to translate it if you don't speak German. That was the fastest source I could come up with.

**Comment by NRmash** [comment]
thx :D
