### ISSUE TITLE
Need help setting up the ASA server

### ISSUE THREAD

**Issue by x-o-i-o-x** [mschnitzer/ark-survival-ascended-linux-container-image#53]
Need help setting up the ASA server.
I installed and set up the container image like in the tutorial but after hours of troubleshooting I couldn't get it to work.
Please write in the comments if you need any additional info.

Thank you so much for helping!

This is what I get when starting the server (and running docker logs -f asa-server-1):

tid(13) burning pthread_key_t == 0 so we never use it
Redirecting stderr to '/home/gameserver/Steam/logs/stderr.txt'
Logging directory: '/home/gameserver/Steam/logs'
minidumps folder is set to /tmp/dumps
[  0%] Checking for available updates...
[----] Verifying installation...
UpdateUI: skip show logoSteam Console Client (c) Valve Corporation - version 1709846822
-- type 'quit' to exit --
Loading Steam API...OK

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
 Update state (0x5) verifying install, progress: 0.19 (11534336 / 6198403134)
 Update state (0x5) verifying install, progress: 11.99 (743306049 / 6198403134)
 Update state (0x5) verifying install, progress: 26.90 (1667113793 / 6198403134)
 Update state (0x5) verifying install, progress: 41.25 (2557045556 / 6198403134)
 Update state (0x5) verifying install, progress: 55.93 (3466887904 / 6198403134)
 Update state (0x5) verifying install, progress: 70.87 (4392516907 / 6198403134)
 Update state (0x5) verifying install, progress: 85.27 (5285639467 / 6198403134)
 Update state (0x5) verifying install, progress: 99.90 (6192001094 / 6198403134)
Success! App '2430930' fully installed.
Starting the ARK: Survival Ascended dedicated server...
Start parameters: TheIsland_WP?listen?Port=7777?RCONPort=27020?RCONEnabled=True -WinLiveMaxPlayers=50 
fsync: up and running.
Failed to read /etc/machine-id, error Invalid argument.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely

Configuration Files:
[docker-compose.txt](https://github.com/mschnitzer/ark-survival-ascended-linux-container-image/files/14542969/docker-compose.txt)
[GameUserSettings.txt](https://github.com/mschnitzer/ark-survival-ascended-linux-container-image/files/14543074/GameUserSettings.txt)

**Comment by x-o-i-o-x** [comment]
I tried your suggestion but it still doesn't work.
After a few minutes the server crashes.

**Comment by mschnitzer** [comment]
What are the specs of the hardware your server is running on?

Please also run the following command and tell me what exit code the container has once it crashes:
```
docker inspect asa-server-1 | grep Exit
```

**Comment by x-o-i-o-x** [comment]
The specs:
OS: Debian GNU/Linux 12 (bookworm) x86_64
Host: ProLiant MicroServer Gen10 Plus
CPU: Intel Xeon E-2224 (4) @ 4.600GHz
Memory: 9564MiB / 15843MiB

By running the above cmd i get this:
           "ExitCode": 0,

**Comment by mschnitzer** [comment]
What does this command return once the server crashes?
```
docker inspect asa-server-1 | grep OOM
```

If your server consumes 9.5 GB of 16 GB already without ARK running, I suspect it runs out of memory. ASA is very RAM consuming. Have you installed any mods?

**Comment by x-o-i-o-x** [comment]
Now it works.
The Problem was that I had a Minecraft server running at the same time with 8GB statically allocated.
Thanks again for helping and the quick response!
