### ISSUE TITLE
Not showing the Session name 

### ISSUE THREAD

**Issue by deronneal0** [mschnitzer/ark-survival-ascended-linux-container-image#62]
After it say the server is up I ran the command to see the session name but nothing is coming back 

Success! App '2430930' fully installed.
Starting the ARK: Survival Ascended dedicated server...
Start parameters: TheIsland_WP?listen?Port=7777?RCONPort=27020?RCONEnabled=True -WinLiveMaxPlayers=50 -clusterid=default -ClusterDirOverride="/home/gameserver/cluster-shared" 
Proton: Upgrading prefix from None to GE-Proton8-21 (/home/gameserver/server-files/steamapps/compatdata/2430930/)
esync: up and running.
Failed to read /etc/machine-id, error Invalid argument.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
docker exec asa-server-1 cat server-files/ShooterGame/Saved/Config/WindowsServer/GameUserSettings.ini | grep SessionName
docker exec asa-server-1 cat server-files/ShooterGame/Saved/Config/WindowsServer/GameUserSettings.ini | grep SessionName

**Comment by deronneal0** [comment]
I figured it out but its not showing up on the `Unofficial` list. Also when creating the Gameuser and Game.ini  how do i find the fold to make them in? Is it the same folder  that the Docker- Compose. yml file or somewhere else.

docker stop asa-server-1
^C
root@TheBatServer:/home/deron/asa-server# ^[[200~docker exec asa-server-1 cat server-files/ShooterGame/Saved/Config/WindowsServer/GameUserSettings.ini | grep SessionName~
docker: command not found
root@TheBatServer:/home/deron/asa-server# docker exec asa-server-1 cat server-files/ShooterGame/Saved/Config/WindowsServer/GameUserSettings.ini | grep SessionName
SessionName=ARK #476639
root@TheBatServer:/home/deron/asa-server# docker exec asa-server-1 cat server-files/ShooterGame/Saved/Config/WindowsServer/GameUserSettings.ini | grep SessionName
SessionName=ARK #476639
root@TheBatServer:/home/deron/asa-server#

**Comment by mschnitzer** [comment]
For the server not showing up issue, did you try [this](https://github.com/mschnitzer/ark-survival-ascended-linux-container-image?tab=readme-ov-file#common-issues)?

As for the Game.ini and GameUserSettings.ini, it is documented [here](https://github.com/mschnitzer/ark-survival-ascended-linux-container-image?tab=readme-ov-file#5-server-configuration) how to edit both ini files.

**Comment by deronneal0** [comment]
Well damn lol. Thank you so much ! I didn't notice this wasnt checked. 

As for the Game. ini and gameusersetting.ini. I cant find /var/lib/docker/volumes/asa-server_server-files-1/_data/ShooterGame/Saved/Config/WindowsServer. 

and thanks a bunch for making this and helping me. This is my first Linux gaming sever and this has helped me so much

**Comment by deronneal0** [comment]
Do I add it to the asa-server folder? There is one already in there but its saying i dont have permission to save anything or delete it.

**Comment by mschnitzer** [comment]
Can you enter the path `/var/lib/docker/volumes/` on your host and run `ls -l` and share the output with me? You need to be root to access that directory.

**Comment by deronneal0** [comment]
root@TheBatServer:/home/deron# /var/lib/docker/volumes/
bash: /var/lib/docker/volumes/: Is a directory
root@TheBatServer:/home/deron# ls -l
total 44
drwxr-xr-x 2 root  root  4096 Apr 27 01:25 asa-server
drwxr-xr-x 2 deron deron 4096 Apr 22 14:37 Desktop
drwxr-xr-x 2 deron deron 4096 Apr 22 14:37 Documents
drwxr-xr-x 2 deron deron 4096 Apr 27 14:31 Downloads
-rw-rw-r-- 1 deron deron 3602 Apr 27 14:32 Game.ini
drwxr-xr-x 2 deron deron 4096 Apr 22 14:37 Music
drwxr-xr-x 2 deron deron 4096 Apr 22 14:37 Pictures
drwxr-xr-x 2 deron deron 4096 Apr 22 14:37 Public
drwx------ 5 deron deron 4096 Apr 22 15:26 snap
drwxr-xr-x 2 deron deron 4096 Apr 22 14:37 Templates
drwxr-xr-x 2 deron deron 4096 Apr 22 14:37 Videos

**Comment by mschnitzer** [comment]
You need to put `cd` in front of ``/var/lib/dokcer/volumes`, so that it becomes: `cd /var/lib/docker/volumes`

The output you are showing says that entering the directory failed, as bash assumes you want to run a command, as you left out the `cd` in front of it. Because of the switch to the other directory failed, you ran `ls -l` on your current location, which in your case was your home.

**Comment by deronneal0** [comment]
root@TheBatServer:/home/deron# cd /var/lib/docker/volumes
root@TheBatServer:/var/lib/docker/volumes# ls -l
total 40
drwx-----x 3 root root  4096 Apr 27 00:17 asa-server_cluster-shared
drwx-----x 3 root root  4096 Apr 27 00:17 asa-server_server-files-1
drwx-----x 3 root root  4096 Apr 27 00:17 asa-server_steam-1
drwx-----x 3 root root  4096 Apr 27 00:17 asa-server_steamcmd-1
brw------- 1 root root  8, 2 Apr 27 13:10 backingFsBlockDev
-rw------- 1 root root 32768 Apr 27 13:10 metadata.db

**Comment by deronneal0** [comment]
backingFsBlockDev is a different color if that makes a difference

**Comment by mschnitzer** [comment]
You can ignore `backingFsBlockDev`.

Can you access `/var/lib/docker/volumes/asa-server_server-files-1/_data/ShooterGame/Saved/Config/WindowsServer` at all (as root user on the host) ? You should find the inis there. If that's not the case, what is the content of that directory?

As I said before, you need to make sure to access that directory as `root` user.

**Comment by deronneal0** [comment]
I Found it! and i assume i can just ass the Game.ini to this same folder?

**Comment by mschnitzer** [comment]
Yes, the `Game.ini` needs to be created in that directory as well. Make sure that it is owned by uid & gid 25000: `chown 25000:25000 Game.ini`

It sets the permissions automatically if you run `docker-compose up -d` again.

**Comment by deronneal0** [comment]
And i add that to docker-compose.yml file?

**Comment by mschnitzer** [comment]
No, you just put it in the same directory like the `GameUserSettings.ini`. The `docker-compose.yml` won't be touched. See this section: https://github.com/mschnitzer/ark-survival-ascended-linux-container-image?tab=readme-ov-file#5-server-configuration

**Comment by deronneal0** [comment]
Awesome That you so much for helping and making this. I really appreciate all the help

**Comment by deronneal0** [comment]
Awesome That you so much for helping and making this. I really appreciate all the help you have given me

**Comment by deronneal0** [comment]
Sorry to rebug you i got  the files where the need to go but now i cant get the server to start. I used docker start asa-server-1 command but it did do anything. Im i doing something wrong

**Comment by mschnitzer** [comment]
`docker-compose` commands almost in all cases require the `yml` to be present in the same directory, from which you are running your `docker-compose` commands from. In your case, it seems that `/home/deron` doesn't have any `yml` specification present.

**Comment by deronneal0** [comment]
![Screenshot from 2024-05-13 15-21-01](https://github.com/mschnitzer/ark-survival-ascended-linux-container-image/assets/44928047/3f249c5e-e7cf-4c6e-a54f-4cf357ef5897)
This is where the docker file is. Im not sure what command i use to start the server

**Comment by kalewenn** [comment]
> This is where the docker file is. Im not sure what command i use to start the server

You have to go in the directory where the file is, then execute your docker compose command :

`cd ~/asa-server`

`docker-compose start asa-server-1`

**Comment by deronneal0** [comment]
root@TheBatServer:/home/deron/asa-server# docker-compose up -d
Starting asa-server_set-permissions-1_1 ... done
Starting asa-server-1                   ... done
root@TheBatServer:/home/deron/asa-server# docker-compose start asa-server-1
Starting asa-server-1 ... done
root@TheBatServer:/home/deron/asa-server# 

Does this mean the server is up and running

**Comment by kalewenn** [comment]
This mean that the docker container is running.

The ark server is running inside the container, to check if all is good, you have to check the ark server logs, I think that the default directory is : 

`/var/lib/docker/volumes/asa-server_server-files-1/_data/ShooterGame/Saved/Logs/`

**Comment by mschnitzer** [comment]
You can check whether the server is running by running `docker ps`. If the ASA container is shown, it is running.

But you are confusing the location of the ini files with the location of the `docker-compose.yml`. The `docker-compose.yml` can live wherever you want, but the `ini` files must be in the volume location `/var/lib/docker/volumes/asa-server_server-files-1/_data/ShooterGame/Saved/Config/WindowsServer`.

**Comment by deronneal0** [comment]
that game ini. I put in there by mistake

**Comment by mschnitzer** [comment]
OK, so all of your questions have been answered now?

**Comment by deronneal0** [comment]
Yup! all my question have been answered

**Comment by deronneal0** [comment]
I got the server running. but for some reason when i added a few mods only 1 showed. after restarting it none of the mods showed.

**Comment by mschnitzer** [comment]
Please open a separate issue for this.
