### ISSUE TITLE
'Failed to cache rpm database' during build

### ISSUE THREAD

**Issue by kalewenn** [mschnitzer/ark-survival-ascended-linux-container-image#68]
Hello,
I'm on **Ubuntu 23.04** & trying to build the repo using 
`make build`

but I have this error : 
`KiwiInstallPhaseFailed: System package installation failed: Target initialization failed: Failed to cache rpm database (1).`

Full logs : 

```
[ INFO    ]: 15:36:17 | Installing system (chroot) for build type: docker
[ INFO    ]: 15:36:17 | --> collection type: onlyRequired
[ INFO    ]: 15:36:17 | --> package: gcc-c++
[ INFO    ]: 15:36:17 | --> package: glibc-locale-base
[ INFO    ]: 15:36:17 | --> package: libfreetype6
[ INFO    ]: 15:36:17 | --> package: libgcc_s1-32bit
[ INFO    ]: 15:36:17 | --> package: make
[ INFO    ]: 15:36:17 | --> package: patterns-base-base
[ INFO    ]: 15:36:17 | --> package: python3
[ INFO    ]: 15:36:17 | --> package: ruby3.3
[ INFO    ]: 15:36:17 | --> package: ruby3.3-devel
[ INFO    ]: 15:36:17 | --> package: tar
[ INFO    ]: 15:36:17 | --> package: timezone
[ INFO    ]: 15:36:17 | --> package: wget
[ DEBUG   ]: 15:36:17 | EXEC: [chroot /root/sources/ark-survival-ascended-linux-container-image/build-results/build/image-root zypper --non-interactive --gpg-auto-import-keys --pkg-cache-dir /var/cache/kiwi/packages --reposd-dir /var/cache/kiwi/zypper/repos --solv-cache-dir /var/cache/kiwi/zypper/solv --cache-dir /var/cache/kiwi/zypper --raw-cache-dir /var/cache/kiwi/zypper/raw --config /kiwi_7p00nzbh install --download in-advance --auto-agree-with-licenses --no-recommends -- gcc-c++ glibc-locale-base libfreetype6 libgcc_s1-32bit make patterns-base-base python3 ruby3.3 ruby3.3-devel tar timezone wget]
[ INFO    ]: Processing: [########################################] 100%
[ ERROR   ]: 15:36:17 | KiwiInstallPhaseFailed: System package installation failed: Target initialization failed:
Failed to cache rpm database (1).
History:
 - 'rpmdb2solv' '-r' '/' '-D' '/usr/lib/sysimage/rpm' '-X' '-p' '/etc/products.d' '/var/cache/kiwi/zypper/solv/@System/solv' '-o' '/var/cache/kiwi/zypper/solv/@System/solvvyrUXl'
   rpmdb2solv: no error


[ INFO    ]: 15:36:17 | Cleaning up SystemPrepare instance
```

Can you tell me why please ? Thanks for help <3
Additional informations : 

- KIWI (next generation) version 9.24.56
- zypper 1.14.42

**Comment by mschnitzer** [comment]
How did you install kiwi on Ubuntu? In any case, as it is documented [here](https://osinside.github.io/kiwi/troubleshooting/buildhost_constraints.html) the host system requires rpm to be available, because you are trying to build a docker image based on openSUSE Leap 15.5.

I know that Ubuntu uses `apt` while openSUSE uses `rpm` as package manager. Is possible to install `rpm` tools on Ubuntu as well? If yes, you can try to install these, maybe this helps you building an image.

I actually wasn't aware of this limitation of kiwi. I assumed you can just build docker images based on any distribution while being host OS agnostic.

If that doesn't help, I'd suggest creating an openSUSE Leap 15.5 VM and install kiwi-ng by running `zypper in -y python3-kiwi make` as root user. Then run `make build load` again and it should work.

**Comment by kalewenn** [comment]
> How did you install kiwi on Ubuntu? In any case, as it is documented [here](https://osinside.github.io/kiwi/troubleshooting/buildhost_constraints.html) the host system requires rpm to be available, because you are trying to build a docker image based on openSUSE Leap 15.5.

`apt install kiwi`

> I know that Ubuntu uses `apt` while openSUSE uses `rpm` as package manager. Is it possible to install `rpm` tools on Ubuntu as well? If yes, you can try to install these, maybe this helps you building an image.
> 
> I actually wasn't aware of this limitation of kiwi. I assumed you can just build docker images based on any distribution while being host OS agnostic.


I used 
`apt install rpm`
and
`apt install zypper`

> If that doesn't help, I'd suggest creating an openSUSE Leap 15.5 VM and install kiwi-ng by running `zypper in -y python3-kiwi make` as root user. Then run `make build load` again and it should work.

Ok thanks I will try !
