### ISSUE TITLE
Possibility to monitor the server status

### ISSUE THREAD

**Issue by heusmich** [mschnitzer/ark-survival-ascended-linux-container-image#69]
Hi,

Is there a possibility to monitor the status of the installed servers (if they are stopped or started), for example with a cronjob?
Two days ago I restarted my root server and forgot to start the ASA servers again, so they were unavailable until I manually started them again.

I have some other game servers installed with LinuxGSM and there is a monitor function available.
If it´s not available in this docker image, is it possible to implement it somehow?

Best regards
heusmich

**Comment by mschnitzer** [comment]
The status can be checked by running `docker-compose ps -a`.

If you want to have an auto restart functionality, you can add a `restart: always` statement to the `docker-compose.yml` file below that line:

https://github.com/mschnitzer/ark-survival-ascended-linux-container-image/blob/5a5fc84ab6f1ef77eb796f436e832aa355336fca/docker-compose.yml#L8

**Comment by heusmich** [comment]
OK, thanks for the fast help.
Then I will add this restart command to my docker compose file and restart the server with the "docker-compose up -d" command.

**Comment by mschnitzer** [comment]
Yes, that's the way to go. I'll close the feature then, please reopen if it doesn't work.
