### ISSUE TITLE
Mods issue 

### ISSUE THREAD

**Issue by deronneal0** [mschnitzer/ark-survival-ascended-linux-container-image#73]
i added a few mods but it only 1 showed when starting the server . after restarting all the mods went away

**Comment by mschnitzer** [comment]
Like in the previous issues, I need more information, otherwise it's not possible to help you. How does the `docker-compose.yml` look like? How do you restart the server when you add new mods? What mods are loaded and which aren't?

**Comment by mschnitzer** [comment]
Is this still relevant?

**Comment by deronneal0** [comment]
It can be closed. i have to retry it later this weekend
