### ISSUE TITLE
Setting up cluster help

### ISSUE THREAD

**Issue by apeface11** [mschnitzer/ark-survival-ascended-linux-container-image#79]
Hi, currently I have both servers setup according to the tutorial. Whenever I run each server individually they work fine, but when I try to launch both 1 will crash. Could someone help me with this please

**Comment by mschnitzer** [comment]
I suspect it's because of your hardware specs. What hardware are you running both servers on?

**Comment by mschnitzer** [comment]
@apeface11 can we close this issue?
