### ISSUE TITLE
Server does not display in the steam/ark search tab

### ISSUE THREAD

**Issue by atp-h** [mschnitzer/ark-survival-ascended-linux-container-image#81]
without changes i ran the docker compose file but after a few ours the server still dit not display inside the ark server tab.

**Comment by atp-h** [comment]
Server specs:
Vm inside a proxmox cluster
4CPU
12GB ram
100GB disk

Servername is 334789
I have portforwarded the ports

**Comment by mschnitzer** [comment]
Is there any update?
