### ISSUE TITLE
My server is not getting listed in the server browser

### ISSUE THREAD

**Issue by davidkinnes** [mschnitzer/ark-survival-ascended-linux-container-image#83]
Hi

Thanks for all your work on this, crazy they have made it so hard to run a dedicated server.  

As you can see, I can connect to the server with the open command but if I set a password that doesn't work, and the server is not getting listed in the server browser.  Let me know if you need any more infomration to help me out.  

Thanks again!

![image](https://github.com/user-attachments/assets/391d7587-6712-4fd6-ae40-3ec2794a10c1)

![image](https://github.com/user-attachments/assets/5e953b52-1155-462e-9fed-2b41f037f3bd)

![Screenshot 2024-09-05 at 17 47 12](https://github.com/user-attachments/assets/e34073b7-d7c8-40d8-8aa2-56284e2c2953)

![Screenshot 2024-09-05 at 17 45 57](https://github.com/user-attachments/assets/b1d206d5-8c6e-41f0-8135-b5e721322f41)

**Comment by mschnitzer** [comment]
You need to check the `Show password protected servers` box as well.

**Comment by mschnitzer** [comment]
Please reopen if this continues to be a problem.
