### ISSUE TITLE
Server broken after update ubuntu 22.04

### ISSUE THREAD

**Issue by kg5hfl** [mschnitzer/ark-survival-ascended-linux-container-image#89]
Updated my server last night and restarted the image without issue. This morning I made some changes to the yml and got some naming errors when I ran "sudo docker compose up -d". After completely removing docker and reinstalling it and got no where. Tried several things that I had found without success. I did find a curl update command suggested on a forum that updated docker from get.docker.com ( curl -sSl https://get.docker.com/ | sh ). After that I got it to run, but when I stopped it again and made a change to the yml it gave me the same error as before "Conflict. The container name blah-blah-blah is already in use by container blah-blah-blah." This time I changed the container name in the actual yml to asa-server-1.1 and I was able to run the docker compose command and it came up. 

I tried a few more changes to the yml and the docker compose command is working and the container is spinning up. Not sure what happened here, but maybe this will help someone else.

**Comment by mschnitzer** [comment]
Regarding the name conflict: `docker-compose up -d` creates a container with a specific name (as defined in the `container_name` attribute). It's safe to just delete the container name upon a name conflict, using: `docker rm $name`. There's no data loss, the container will just get recreated with the definition of the yml file once you run `docker-compose up -d`.

Does everything work now?

**Comment by mschnitzer** [comment]
No further reply, closing.
