### ISSUE TITLE
Failed to read /etc/machine-id

### ISSUE THREAD

**Issue by mindzes** [mschnitzer/ark-survival-ascended-linux-container-image#9]
Hello,
I'm complete noob on this. Please could some one explain what I'm doing wrong? Or wat's problem here?
I'm using Ubuntu 22.04.3 LTS

asa-server-1                    | Success! App '2430930' fully installed.
asa-server-1                    | Starting the ARK: Survival Ascended dedicated server...
asa-server-1                    | Start parameters: TheIsland_WP?listen?Port=7777?RCONPort=27020?RCONEnabled=True -WinLiveMaxPlayers=20
asa-server-1                    | esync: up and running.
asa-server-1                    | Failed to read /etc/machine-id, error Invalid argument.
asa-server-1                    | wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
asa-server-1 exited with code 3

**Comment by mschnitzer** [comment]
Hi,

this error can be ignored and is not causing the container to exit with code 3.

Are you running Proxmox or some sort of virtualization?

**Comment by mindzes** [comment]
Yes I'm using Proxmox

**Comment by mschnitzer** [comment]
There was another user who had the same issue and they described [here](https://github.com/mschnitzer/ark-survival-ascended-linux-container-image/issues/6#issuecomment-1793733764) how they solved it.

The `/etc/machine-id` error is unrelated to the exit code 3 error that you are experiencing. The `/etc/machine-id` error occurs, because this file is not present in docker container environments, but that's more like a warning than an error.

**Comment by mindzes** [comment]
Thanks

**Comment by mschnitzer** [comment]
Does it work?

**Comment by mindzes** [comment]
Still failed to read  /etc mashine-id but server not exiting. Now waiting to show up.

Success! App '2430930' fully installed.
Starting the ARK: Survival Ascended dedicated server...
Start parameters: TheIsland_WP?listen?Port=7777?RCONPort=27020?RCONEnabled=True -WinLiveMaxPlayers=20
esync: up and running.
Failed to read /etc/machine-id, error Invalid argument.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely

**Comment by mschnitzer** [comment]
As I said, you can ignore the `/etc/machine-id` "error". It does not have any effect on the stability of the server, this file is not needed and does not exist in the docker container environment.

**Comment by mindzes** [comment]
Working like a clock. Thank you :)
