### ISSUE TITLE
adding -mods flag causing failure to init (?)

### ISSUE THREAD

**Issue by Obe1sance** [mschnitzer/ark-survival-ascended-linux-container-image#90]
I got a server up and running last night on the home lab via Ubuntu server and was playing around (Thank you BTW, the kids will love this). I decided to look into modding it. Documentation made it look simple enough so I added the mod flag to the launch parameters but now the server seemingly fails to launch at all.  I'm curious if I'm missing something here? 

```
 - ASA_START_PARAMS=Aberration_WP?listen?Port=7777?RCONPort=27020?RCONEnabled=True -WinLiveMaxPlayers=12 -mods=929868,947835,949521,931047,961601,946694,929420,928621,1039530,930170,957641 -clusterid=default -ClusterDirOverride="/home/gameserver/cluster-shared"
````

After modifying the launch parameters in the docker-compose.yml I stopped the server then rebuilt using 

```
sudo docker-compose up -d
```

Per documentations instructions (I had to use it with sudo). 

Output:
```
sudo docker-compose up -d
Starting asa-server_set-permissions-1_1 ... done
Starting asa-server-1                   ... done
```

I then started the server with 

```
 sudo docker start asa-server-1
output: asa-server-1
```

But spite having left it alone over night (figured it was downloading mods), it still fails to appear in the server list and I cannot connect via console. 

I tried to start from scratch and figured I'd use tcpdump to monitor whether or not downloads were happening on that server but it doesn't appear that there is any additional traffic. 

About the only thing I can think of is that I've got the wrong mod ID's, but nobody seems to post those on Curse, so I just assumed the "Project ID" = modID?

I appreciate your time. Thank you.

**Comment by Obe1sance** [comment]
Please disregard. There must be a mod inconsistency/conflict as I have been able to get some mods working. Sorry to bother.

**Comment by mschnitzer** [comment]
Closing, all seems to be working.
